---
- hosts: all
  gather_facts: yes
  connection: local

  tasks:
    - name: run show version
      ios_command:
        commands:
          - show version
          - show run
      register: show_run
          
    - name: save output to /etc/ansible/backup 
      copy: 
        content: "{{ show_run.stdout[0] }}"
        dest: "/etc/ansible/backup/show_run_01.txt"
