---
- hosts: all
  gather_facts: yes
  connection: local

  tasks:
    - name: run show version
      ios_command:
        commands:
          - show running-config
          - show interface
      register: show_run
      
    - name: get timestamp
      command: date +%Y%m%d-%H:%M:%S
      register: timestamp
      
    - name: save output to /etc/ansible/backup 
      copy: 
        content: "{{ show_run.stdout[0] }}"
        dest: "/etc/ansible/backup/show_run_{{ timestamp.stdout }}.txt"
