---
- hosts: all
  gather_facts: yes
  connection: local

  tasks:
    - name: show run 
      ios_command:
        commands:
        - show run 

- copy: 
        content: "{{ config.stdout[0] }}"
        dest: /etc/ansible/backup/show_run_01.txt
