---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: show run 
      ios_command:
        commands:
        - show run
      register: show_run

    - copy:
        content: "{{ show_run.stdout[0] }}"
        dest: /tmp/show_run_01.txt
