---
- hosts: all
  gather_facts: yes
  connection: local

  tasks:
    - name: show run 
      ios_command:
        commands:
        - show run
      register: show_run
      
    - debug:
      msg: "{{ show_run.stdout[0] }}"

