---
- hosts: all
  gather_facts: yes
  connection: local

  tasks:
    - name: show run 
      ios_command:
        commands:
        - show run
      register: show_run
    - debug:
        msg: "{{ show_run }}"
        
    - name: save output to /etc/ansible/backup
      copy: 
        content: "{{ config.stdout[0] }}"
        dest: /tmp/show_run_01.txt
