---
- hosts: ios_devices
  gather_facts: no
  connection: local
 
  tasks:
  - name: SYS | Define provider
    set_fact:
      provider:
      username: admin
      password: 1qaz!QAZ

  - name: IOS | Show clock
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show clock
    register: clock
