---
- hosts: 192.168.1.105
  gather_facts: true
  connection: local
 
  tasks:
   - name: show run 
   ios_command:
   commands:
     - show run 
     host: "{{ ansible_host }}"
     username: admin
     password: 1qaz!QAZ
     register: config
