---
- hosts: 192.168.0.105
  gather_facts: true
  connection: local
 
  tasks:
   - name: show run
   host: 192.168.0.105
   username: admin
   password: 1qaz!QAZ
   register: config
   
   ios_command:
   commands: show run 

