---
- hosts: '"Cisco Router"'
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: admin
      password: 1qaz!QAZ

  tasks:
      - name: run show version
        ios_command:
          commands: "show version"
          provider: "{{ cli }}"
        register: show_version
