---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: run show version
      ios_command:
        commands: "show version"
        host: 192.168.1.105
        username: admin
        password: 1qaz!QAZ
        register: show_version

    - name: print the show version output
      debug: var=show_version
