---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: run show version
      host: 192.168.1.105
      username: admin
      password: 1qaz!QAZ 
      ios_command:
        commands: show version
        wait_for:
          - result[0] contains IOS        


