---
- hosts: 192.168.1.105
  connection: local
  vars:
    cli:
      host: 192.168.1.105
      username: admin
      password: 1qaz!QAZ

  tasks:
      - name: run show version
        ios_command:
          commands: "show version"
          provider: "cli"
        register: show_version

      - name: print the show version output
        debug: var=show_version
