---
- hosts: localhost    # 実機を対象としない。ここではダミー的に localhost とする
  gather_facts: no
  connection: local

  tasks:
    - name: run show version
      ios_command:
        commands: "show version"
        username: admin
        password: 1qaz!QAZ
        register: show_version

    - name: print the show version output
      debug: var=show_version
