---

- hosts: 192.168.1.105
  gather_facts: no

tasks:
  - name: run show version
    ios_command: 
      commands: show version
      host: 192.168.1.105
      username: admin
      password: 1qaz!QAZ
