---

- hosts: all
  gather_facts: no

  tasks:
   - name: crawl config file
     local_action:
       module: ios_command
       authorize: yes
       auth_pass: 1qaz!QAZ
       username: admin
       password: 1qaz!QAZ
       host: 192.168.1.105
       commands:
         - show run
     register: result
