---
- hosts: all
  gather_facts: yes
  connection: local

  tasks:
    - name: Adding Access List
      ios_config:
        parents: "ip access-list extended TEST-ACL"
        lines:
          - permit tcp any any eq smtp
          - permit tcp any any eq www
        before: "no ip access-list extended TEST-ACL"
