---
- hosts: all
  gather_facts: yes
  connection: local

  tasks:
    - name: Adding Access List
      ios_config:
        lines: access-list 100 deny icmp any any
      before: "no ip access-list 100"
